---

- name: DMARC - enabled
  when: rspamd_dmarc_active | bool
  block:

    - name: Enable DMARC by rspamd
      ansible.builtin.template:
        src: dmarc.conf.j2
        dest: /etc/rspamd/local.d/dmarc.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart rspamd

    - name: Schedule dmarc reporting
      ansible.builtin.cron:
        name: DMARC reporting
        weekday: '*'
        minute: '00'
        hour: '*'
        user: "{{ rspamd_learning_user }}"
        job: rspamadm dmarc_report
        cron_file: rspamd-dmarc
      when: rspamd_learning_user is defined and rspamd_learning_user | length > 0

- name: DMARC - disabled
  when: not rspamd_dmarc_active | bool
  block:

    - name: Disable DMARC by rspamd
      ansible.builtin.copy:
        content: |
          enabled = false;
        dest: /etc/rspamd/local.d/dmarc.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart rspamd
