---

- name: Configuring postfix (main.cf)
  lineinfile:
    path:   /etc/postfix/main.cf
    regexp: "^(#)?{{ item.key }}(\\s)?=.*"
    line:   "{{ item.key }} = {{ (item.value|join(', ')) if item.value|type_debug == 'list' else item.value }}"
  loop: "{{ rspamd_postfix | dict2items }}"
  notify: Restart postfix
