---

- name: Get current smtpd_milter setting
  shell: |
    grep "^smtpd_milter" /etc/postfix/main.cf | sed "s/.* = //"
  changed_when: false
  check_mode: false
  register: _milters

- name: Merge smtpd_milters
  set_fact:
    smtpd_milters: "{{ ( _milters.stdout.split(',') + [ rspamd_postfix.smtpd_milters ] ) | unique }}"

- name: Configuring postfix (main.cf)
  lineinfile:
    path:   "/etc/postfix/main.cf"
    regexp: "^(#)?{{ item.key }}(\\s)?=.*"
    line: >-
      {%- if item.key == 'smtpd_milters' -%}
      {{ item.key }} = {{ smtpd_milters | join(',') }}
      {%- else -%}
      {{ item.key }} = {{ (item.value|join(', ')) if item.value|type_debug == 'list' else item.value }}
      {%- endif -%}
  loop: "{{ rspamd_postfix | dict2items }}"
  notify: Restart postfix
