---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    rspamd_organization: Example Inc
    rspamd_controller_password: $2$hrr3pjpiie499r1e7tb1p4qxm84mqeo9$rkgidupktocmsiog5wnm6z93ui9t8jrqpw8ta4sq8dty6djo5bdb
    rspamd_domains: ['example.com', 'foo.bar']
    dovecot_ssl_key: "{{ openssl_server_key }}"
    dovecot_ssl_chain: "{{ openssl_server_crt }}"
    dovecot_domain: example.com
    postfix_ipv6: False
    postfix_domain: example.com
    postfix_fqdn: host.example.com
    postfix_ssl_key: "{{ openssl_server_key }}"
    postfix_ssl_chain: "{{ openssl_server_crt }}"
  roles:
    - deitkrachten.cron
    - deitkrachten.openssl
    - deitkrachten.postfix
  tasks:
    - name: Include role 'ansible-role-rspamd'
      ansible.builtin.include_role:
        name: ansible-role-rspamd
